apiVersion: v1
kind: Pod
metadata:
  name: login-pod-hostpath-volume
  labels:
    app: login-app
spec:
  containers:
  - name: login-app
    image: prchekuri/login-2514:poornima
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        memory: "256Mi"
        cpu: "300m"
    volumeMounts:
      - name: host-logs
        mountPath:  /usr/share/nginx/html
    ports:
      - containerPort: 80
  volumes: 
    - name: host-logs
      hostPath:
        path: /data/login-app-logs
        type: DirectoryOrCreate

