apiVersion: v1
kind: Pod
metadata:
  name: higher-priority
  labels:
    app: higher-priority
spec:
  nodeName: gke-prudhvi-k8s-cluster-default-pool-5e6e1f73-479l
  containers:
  - name: login-app
    image: prchekuri/login-2514:poornima
    resources:
      requests:
        cpu: "800m"
    ports:
      - containerPort: 80