apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
           matchExpressions:
              - key: app
                operator: In
                values:
                - login-app
          topologyKey: "kubernetes.io/hostname"
        - labelSelector:
           matchExpressions:
              - key: pod
                operator: In
                values:
                - node-anti-affinity-pod
          topologyKey: "kubernetes.io/hostname"
  containers:
    - name: nginx
      image: nginx