apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
          topologyKey: kubernetes.io/hostname
          matchExpressions:
              - key: app
                operator: In
                values:
                - login-app
  containers:
    - name: nginx
      image: nginx