apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
             - key: app
               operator: In
               values:
               - login-app
          topologyKey: "kubernetes.io/hostname"
  tolerations:
  - key: "master"
    operator: "Equal"
    value: "true"
    effect: NoSchedule
  containers:
    - name: nginx
      image: nginx