apiVersion: v1
kind: Pod
metadata:
  name: very-very-low-priority
  labels:
    app: very-low-priority
spec:
  nodeName: gke-prudhvi-k8s-cluster-default-pool-5e6e1f73-w7sr
  priorityClassName:  very-very-low-priority
  containers:
  - name: login-app
    image: prchekuri/login-2514:poornima
    resources:
      requests:
        cpu: "200m"
    ports:
      - containerPort: 80