apiVersion: v1
kind: Pod
metadata:
  name: very-low-priority
  labels:
    app: very-low-priority
spec:
  priorityClassName:  very-low-priority
  containers:
  - name: login-app
    image: prchekuri/login-2514:poornima
    resources:
      requests:
        cpu: "300m"
    ports:
      - containerPort: 80