apiVersion: v1
kind: Pod
metadata:
  name: login-pod
  labels:
    app: login-app
spec:
  volumes:
    - name: login-shared-volume
      emptyDir: {}
  initContainers:
  - name: login-init-cont
    image: busybox
    command:
      - sh
      - -c
      - echo "<p>login-app is initialized</p>" > /app-data/index.html
    volumeMounts:
      - name: login-shared-volume
        mountPath: /app-data
  containers:
  - name: login-app
    image: prchekuri/login-2514:poornima
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        memory: "256Mi"
        cpu: "300m"
    volumeMounts:
      - name: login-shared-volume
        mountPath: usr/shar/nginx/html
    ports:
      - containerPort: 80
      
