apiVersion: v1
kind: Pod
metadata:
  name: login-app-emptydir-volume
  labels:
    app: login-app
spec:
  volumes:
    - name: login-shared-storage
      emptyDir: {}
  containers:
  - name: myapp
    image: prchekuri/login-2514:poornima
    resources:
      requests:
        cpu:  "100m"
        memory: "128Mi"
      limits:
        memory: "256Mi"
        cpu: "300m"
    volumeMounts:
      - name: login-shared-storage
        mountPath: /tmp/conta
    ports:
      - containerPort: 80
  - name: writer-container
    image:  busybox
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /tmp/contb/time-log.txt;
          echo "writing to shared storage";
          sleep 5;
        done
    volumeMounts:
      - name: login-shared-storage
        mountPath:  /tmp/contb

