apiVersion: v1
kind: Pod
metadata:
  name: lab2-sigkill
spec:
  terminationGracePeriodSeconds: 5
  containers:
  - name: app
    image: busybox
    command:
      - sh
      - -c
      - |
        echo "START"

        trap 'echo "SIGTERM RECEIVED"; sleep 20' TERM

        sleep 300