apiVersion: v1
kind: Pod
metadata:
  name: lab2-sigkill
spec:
  terminationGracePeriodSeconds: 5
  containers:
  - name: app
    image: busybox
    command:
      - sh
      - -c
      - |
        echo "START $(date)"

        trap 'echo "SIGTERM RECEIVED $(date)"; sleep 20' TERM

        while true; do
          echo "RUNNING $(date)"
          sleep 1
        done