apiVersion: v1
kind: Pod
metadata:
  name: lab3-prestop-sigterm
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: app
    image: busybox
    lifecycle: 
      preStop:
        exec:
          command:
            - sh
            - -c
            - |
              echo PRESTOP START >> /tmp/prestop.log
              sleep 6
              echo PRESTOP END >> /tmp/prestop.log
    command:
      - sh
      - -c
      - |
        echo "START $(date)"

        trap 'echo "SIGTERM RECEIVED $(date)"; sleep 2; echo "EXITING CLEANLY $(date)"; exit 0' TERM

        while true; do
          echo "RUNNING $(date)"
          sleep 1
        done