apiVersion: v1
kind: Pod
metadata:
  name: login-log-test
  labels:
    app: login-app
spec:
  containers:
  - name: login-app
    image: busybox
    command: ["sh","-c"]
    args:
      - |
        while true; do
          echo "login success $(date)"
          sleep 5
        done