apiVersion: v1
kind: Pod
metadata:
  name: login-pod
  labels:
    app: login-app
spec:
  nodeName: gke-prudhvi-k8s-cluster-default-pool-5e6e1f73-479l
  containers:
  - name: login-app
    image: prchekuri/login-2514:poornima
    ports:
    - containerPort: 80

