apiVersion: v1
kind: Pod
metadata:
  name: login-pod
  labels:
    app: login-app
spec:
  volumes:
    - name: login-shared-html
      emptyDir: {}
    - name: login-shared-log
      emptyDir: {}
  initContainers:
  - name: login-init-cont
    image: busybox
    command:
      - sh
      - -c
      - echo "<p>login-app is initialized</p>" > /app-data/index.html
    volumeMounts:
      - name: login-shared-html
        mountPath: /app-data
  containers:
  - name: login-app-cont
    image: prchekuri/login-2514:poornima
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        memory: "256Mi"
        cpu: "300m"
    volumeMounts:
      - name: login-shared-html
        mountPath: usr/share/nginx/html
    ports:
      - containerPort: 80
  
  - name: log-stream-sidecar-cont
    image:  busybox
    volumeMounts:
      - name:  login-shared-log
        mountPath: /var/log/app
    command: ["bin/sh"]
    args: 
      - -c
      - |
        tail -n+1 -f /var/log/app/app.log

  - name: log-writer-sidecar-cont
    image:  busybox
    volumeMounts:
      - name:  login-shared-log
        mountPath: /var/log/app
    command: ["bin/sh"]
    args: 
      - -c
      - |
        while true; do
          echo "$(date) login-app running" >> /var/log/app/app.log
          sleep 10
        done
