apiVersion: v1
kind: Pod
metadata:
  name: login-pod
  labels:
    app: login-app
spec:
  containers:
  - name: login-app
    image: prchekuri/login-2514:poornima
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        memory: "256Mi"
        cpu: "300m"
    envFrom:
      - configMapRef:
          name: login-config
    env:
      - name: ENV
        valueFrom:
          configMapKeyRef:
            name: login-config
            key: APP_MODE
      - name: LOG
        valueFrom:
          configMapKeyRef:
            name: login-config
            key:  LOG_LEVEL

    ports:
      - containerPort: 80